# CREATE Organisation TABLE

# --- !Ups

CREATE TABLE organisations (
  ID         UUID         NOT NULL PRIMARY KEY,
  CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_DATE,
  UPDATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_DATE,

  NAME       VARCHAR(255) NOT NULL,
  TOKEN      VARCHAR(255)
);

# --- !Downs

DROP TABLE organisations;
